runtime: python
env: flex
api_version: 1
threadsafe: true

runtime_config:
  python_version: 3

handlers:
- url: /.*
  script: main.app

beta_settings:
  cloud_sql_instances: game-lookup:us-central1:gamelookup